#Download base image ubuntu 16.04
FROM ubuntu:16.04

RUN apt-get update -y && apt-get upgrade -y

RUN apt-get install -y make g++ libboost-program-options1.58.0 libboost-filesystem1.58.0 libboost-system1.58.0 
